import Head from "next/head";
import PoiCard from "@/components/PoiCard";
import { pois } from "@/lib/pois";

export default function Home() {
  return (
    <>
      <Head>
        <title>POI-Chat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PoiCard pois={pois} />
      </main>
    </>
  );
}
